title: KelasPajakWithLess
description: Mudahnya belajar perpajakan Indonesia
permalink: pretty
twitter_username: kelaspajakwith1
instagram: kelaspajakwith

baseurl: /rhinotail

repository: kelaspajak/rhinotail
encoding: UTF-8

exclude:
  - Gemfile*
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - node_modules
  - _submodules
  - script
  - vendor
  - .travis.yml
  - ".git*"
  - bin

markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass

collections:
  fitur:
    output: true
    permalink: /:collection/:path
    screenshots: /assets/screenshot/logos.jpg


include:
  - _pages


defaults:
  - scope:
      path: ""
      type: fitur
    values:
      layout: detail
  - scope:
      path: "assets/img"
    values:
      image: true

plugins:
  - jekyll-octicons
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  
branch: master

# Google Analytics
google_analytics: UA-146778045-2